# Generated by Django 3.2 on 2022-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_orderlineitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
