# Generated by Django 3.2 on 2022-07-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderlineitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
