# Generated by Django 3.2 on 2022-06-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='title',
            new_name='name',
        ),
    ]
