# Generated by Django 3.2 on 2022-06-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_title_package_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
