# Generated by Django 3.2 on 2022-07-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220621_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tier',
        ),
    ]
